apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: veloura
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: veloura-store
    newName: ghcr.io/akdavid4real/veloura-store
    newTag: latest
